---
- name: "Create Backend app directory"
  file:
    path: ~/backend-app
    state: directory
- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app
- name: "Installing Dependencies"
  shell: |
    cd ~/backend-app
    npm i
- name: "Executing app with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: output

- name:  "print status of executing the backend app"
  debug:
    msg: "{{output.stdout_lines}}"

- name : "run pm2 as a service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu